spring.application.name=catalog-service
server.port=8081

spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://${MONGO_ROOT_USERNAME:admin}:${MONGO_ROOT_PASSWORD:mongo_dev_password}@localhost:27017/${MONGO_CATALOG_DB:catalog_db}?authSource=admin}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.jackson.default-property-inclusion=non_null
