spring.application.name=catalog-service
server.port=8081

spring.mongodb.uri=mongodb://admin:mongo_dev_password@localhost:27017/catalog_db?authSource=admin

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.jackson.default-property-inclusion=non_null
